<script>
  import { t } from '$lib/i18n.js';
  import { getInspections } from '$lib/api/audit.js';
  import { onMount } from 'svelte';
  import { Info, BadgeCheck, BadgeAlert } from '@lucide/svelte';

  let batches = $state([]);
  let loading = $state(true);
  let error = $state('');

  let dateFrom = $state('');
  let dateTo = $state('');
  let activeQuickFilter = $state('');
  let isQuickFilterActive = false;

  // Pagination states
  let page = $state(1);
  let limit = $state(10);
  let totalPages = $derived(Math.ceil(batches.length / limit) || 1);
  let paginatedBatches = $derived(batches.slice((page - 1) * limit, page * limit));

  async function fetchTraceability() {
    loading = true;
    error = '';
    try {
      const params = { limit: 1000 };
      if (dateFrom) params.dateFrom = `${dateFrom}T00:00:00`;
      if (dateTo) params.dateTo = `${dateTo}T23:59:59`;
      const result = await getInspections(params);
      const inspections = result.data || [];
      
      const batchMap = {};
      inspections.forEach(item => {
        // Generate batch ID based on date if not provided
        let batchId = item.batchId;
        let isAutoGenerated = false;
        
        if (!batchId || batchId === 'null') {
          const date = new Date(item.timestamp);
          const year = date.getFullYear();
          const month = String(date.getMonth() + 1).padStart(2, '0');
          const day = String(date.getDate()).padStart(2, '0');
          const dateStr = `${year}-${month}-${day}`;
          batchId = `AUTO-${dateStr}`;
          isAutoGenerated = true;
        }
        
        if (!batchMap[batchId]) {
          batchMap[batchId] = { total: 0, passed: 0, failed: 0, isAutoGenerated };
        }
        batchMap[batchId].total++;
        // Check for both OK and GOOD status
        if (item.status === 'GOOD' || item.status === 'OK') {
          batchMap[batchId].passed++;
        } else {
          batchMap[batchId].failed++;
        }
      });
      
      console.log('Batch Map:', batchMap);
      console.log('Total inspections:', inspections.length);
      
      batches = Object.entries(batchMap)
        .map(([id, stats]) => ({
          id,
          ...stats,
          passRate: stats.total > 0 ? ((stats.passed / stats.total) * 100).toFixed(1) : 0,
          verified: stats.total > 0,
        }))
        .sort((a, b) => b.id.localeCompare(a.id)); // Sort by batch ID descending (newest first)
      
      console.log('Batches:', batches);
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  function setQuickFilter(type) {
    isQuickFilterActive = true;
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    dateTo = `${year}-${month}-${day}`;
    
    if (type === 'today') {
      dateFrom = dateTo;
      activeQuickFilter = 'today';
    } else if (type === 'week') {
      const weekAgo = new Date(today);
      weekAgo.setDate(today.getDate() - 7);
      const wYear = weekAgo.getFullYear();
      const wMonth = String(weekAgo.getMonth() + 1).padStart(2, '0');
      const wDay = String(weekAgo.getDate()).padStart(2, '0');
      dateFrom = `${wYear}-${wMonth}-${wDay}`;
      activeQuickFilter = 'week';
    } else if (type === 'month') {
      const monthAgo = new Date(today);
      monthAgo.setMonth(today.getMonth() - 1);
      const mYear = monthAgo.getFullYear();
      const mMonth = String(monthAgo.getMonth() + 1).padStart(2, '0');
      const mDay = String(monthAgo.getDate()).padStart(2, '0');
      dateFrom = `${mYear}-${mMonth}-${mDay}`;
      activeQuickFilter = 'month';
    }
  }

  function goToPage(p) {
    page = p;
  }

  onMount(() => {
    fetchTraceability();
  });

  let searchTimer;
  $effect(() => {
    dateFrom; dateTo;
    if (!isQuickFilterActive && activeQuickFilter) {
      activeQuickFilter = '';
    }
    isQuickFilterActive = false;
    clearTimeout(searchTimer);
    searchTimer = setTimeout(() => {
      page = 1;
      fetchTraceability();
    }, 300);
  });
</script>

<svelte:head><title>{$t('auditor.traceability')} — EPSON QC</title></svelte:head>

<div class="page animate-fade-in">
  <h1 class="page-title">{$t('auditor.traceability')}</h1>
  <p class="subtitle">
    Pelacakan produk berdasarkan batch produksi. 
    <span class="info-badge">
      <Info size={12} class="inline-icon" />
      Batch dengan prefix "AUTO-" di-generate otomatis dari tanggal inspeksi
    </span>
  </p>

  <div class="filter-row">
    <div class="quick-filters">
      <button class="quick-btn" class:active={activeQuickFilter === 'today'} onclick={() => setQuickFilter('today')}>Hari Ini</button>
      <button class="quick-btn" class:active={activeQuickFilter === 'week'} onclick={() => setQuickFilter('week')}>Minggu Ini</button>
      <button class="quick-btn" class:active={activeQuickFilter === 'month'} onclick={() => setQuickFilter('month')}>Bulan Ini</button>
    </div>
    <div class="date-filter-group">
      <label class="date-label">Dari:</label>
      <input type="date" class="date-input" bind:value={dateFrom} />
    </div>
    <div class="date-filter-group">
      <label class="date-label">Sampai:</label>
      <input type="date" class="date-input" bind:value={dateTo} />
    </div>
  </div>

  {#if dateFrom || dateTo}
    <div class="date-range-info">
      Data rentang waktu {dateFrom || '...'} ke {dateTo || '...'}
    </div>
  {/if}
  {#if error}
    <div class="error-banner">{error}</div>
  {/if}

  {#if loading}
    <div class="loading-state">{$t('common.loading')}</div>
  {:else}
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>{$t('auditor.batch_id')}</th>
          <th>Total Parts</th>
          <th>Passed</th>
          <th>Failed</th>
          <th>Pass Rate</th>
          <th>{$t('auditor.verified')}</th>
        </tr>
      </thead>
      <tbody>
        {#each paginatedBatches as batch}
          <tr>
            <td>
              <code class:auto-batch={batch.isAutoGenerated}>{batch.id}</code>
            </td>
            <td>{batch.total}</td>
            <td class="ok-text">{batch.passed}</td>
            <td class="ng-text">{batch.failed}</td>
            <td>
              <span class="pass-rate" class:high={batch.passRate >= 95} class:medium={batch.passRate >= 80 && batch.passRate < 95} class:low={batch.passRate < 80}>
                {batch.passRate}%
              </span>
            </td>
            <td>
              <span class="badge" class:badge-ok={batch.verified} class:badge-ng={!batch.verified}>
                {#if batch.verified}
                  <BadgeCheck size={13} class="inline-icon" /> {$t('auditor.verified')}
                {:else}
                  <BadgeAlert size={13} class="inline-icon" /> Unverified
                {/if}
              </span>
            </td>
          </tr>
        {/each}
        {#if batches.length === 0}
          <tr><td colspan="6" class="no-data">{$t('common.no_data')}</td></tr>
        {/if}
      </tbody>
    </table>
  </div>

  <div class="table-footer">
    <span>{$t('common.showing')} {batches.length > 0 ? (page-1)*limit + 1 : 0}-{Math.min(page*limit, batches.length)} {$t('common.of')} {batches.length}</span>
    {#if totalPages > 1}
      <div class="pagination">
        <button class="btn btn-ghost" disabled={page <= 1} onclick={() => goToPage(page - 1)}>{$t('common.prev')}</button>
        <span class="page-num">{page}/{totalPages}</span>
        <button class="btn btn-ghost" disabled={page >= totalPages} onclick={() => goToPage(page + 1)}>{$t('common.next')}</button>
      </div>
    {/if}
  </div>
  {/if}
</div>

<style>
  .page-title { font-size: var(--fs-xl); font-weight: var(--fw-semibold); margin-bottom: var(--sp-2); }
  .subtitle { color: var(--clr-text-dim); font-size: var(--fs-sm); margin-bottom: var(--sp-5); }
  .info-badge { 
    display: inline-flex;
    align-items: center;
    gap: 4px;
    background: var(--clr-surface-2); 
    padding: 3px 8px; 
    border-radius: var(--radius-sm); 
    font-size: var(--fs-xs);
    margin-left: var(--sp-2);
    vertical-align: middle;
  }
  .filter-row { display: flex; gap: var(--sp-3); margin-bottom: var(--sp-4); flex-wrap: wrap; align-items: center; }
  .quick-filters { display: flex; gap: var(--sp-2); }
  .quick-btn {
    padding: var(--sp-2) var(--sp-3);
    font-family: var(--font-family);
    font-size: var(--fs-xs);
    font-weight: var(--fw-medium);
    color: var(--clr-text-muted);
    background: var(--clr-surface);
    border: 1px solid var(--clr-border);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
  }
  .quick-btn:hover {
    background: var(--clr-surface-2);
    border-color: var(--clr-border-light);
  }
  .quick-btn.active {
    background: var(--clr-accent);
    color: white;
    border-color: var(--clr-accent);
  }
  .quick-btn:active {
    transform: scale(0.98);
  }
  .date-filter-group { display: flex; align-items: center; gap: var(--sp-2); }
  .date-label { font-size: var(--fs-sm); color: var(--clr-text-muted); font-weight: var(--fw-medium); white-space: nowrap; }
  .date-input {
    padding: var(--sp-2) var(--sp-3);
    font-family: var(--font-family);
    font-size: var(--fs-sm);
    color: var(--clr-text);
    background: var(--clr-surface);
    border: 1px solid var(--clr-border);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
  }
  .date-input:hover { border-color: var(--clr-border-light); }
  .date-input:focus {
    outline: none;
    border-color: var(--clr-accent);
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
  }
  .date-range-info {
    font-size: var(--fs-sm);
    color: var(--clr-text-muted);
    padding: var(--sp-2) var(--sp-3);
    background: var(--clr-surface);
    border-left: 3px solid var(--clr-accent);
    border-radius: var(--radius-sm);
    margin-bottom: var(--sp-3);
  }
  .error-banner { padding: var(--sp-3); background: var(--clr-ng-bg); color: var(--clr-ng); border-radius: var(--radius-md); font-size: var(--fs-sm); margin-bottom: var(--sp-4); border: 1px solid rgba(239,68,68,0.2); }
  .loading-state { padding: var(--sp-8); text-align: center; color: var(--clr-text-muted); }
  .no-data { text-align: center; color: var(--clr-text-dim); padding: var(--sp-8) !important; }
  code { background: var(--clr-surface-2); padding: 1px 6px; border-radius: 4px; font-size: var(--fs-xs); }
  code.auto-batch { background: rgba(59, 130, 246, 0.1); color: var(--clr-accent); }
  .ok-text { color: var(--clr-ok); font-weight: var(--fw-medium); }
  .ng-text { color: var(--clr-ng); font-weight: var(--fw-medium); }
  .pass-rate { font-weight: var(--fw-semibold); padding: 2px 8px; border-radius: var(--radius-sm); }
  .pass-rate.high { color: var(--clr-ok); background: var(--clr-ok-bg); }
  .pass-rate.medium { color: var(--clr-warning); background: rgba(251, 191, 36, 0.1); }
  .pass-rate.low { color: var(--clr-ng); background: var(--clr-ng-bg); }
  
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 3px 8px;
  }
  .badge :global(.inline-icon), .info-badge :global(.inline-icon) {
    display: inline-block;
    vertical-align: middle;
  }
  .table-footer { margin-top: var(--sp-3); font-size: var(--fs-xs); color: var(--clr-text-dim); display: flex; justify-content: space-between; align-items: center; }
  .pagination { display: flex; align-items: center; gap: var(--sp-2); }
  .page-num { font-weight: var(--fw-medium); color: var(--clr-text-muted); }
  .page { display: flex; flex-direction: column; flex: 1; overflow: hidden; height: 100%; }
  .table-container { flex: 1; overflow-y: auto; }
</style>
