<script>
  import { t } from '$lib/i18n.js';
  import { getInspections } from '$lib/api/audit.js';
  import { onMount } from 'svelte';

  let batches = $state([]);
  let loading = $state(true);
  let error = $state('');

  async function fetchTraceability() {
    loading = true;
    error = '';
    try {
      const result = await getInspections({ limit: 1000 });
      const inspections = result.data || [];
      
      const batchMap = {};
      inspections.forEach(item => {
        // Generate batch ID based on date if not provided
        let batchId = item.batchId;
        let isAutoGenerated = false;
        
        if (!batchId || batchId === 'null') {
          const date = new Date(item.timestamp);
          const dateStr = date.toISOString().split('T')[0]; // YYYY-MM-DD
          batchId = `AUTO-${dateStr}`;
          isAutoGenerated = true;
        }
        
        if (!batchMap[batchId]) {
          batchMap[batchId] = { total: 0, passed: 0, failed: 0, isAutoGenerated };
        }
        batchMap[batchId].total++;
        // Check for both OK and GOOD status
        if (item.status === 'GOOD' || item.status === 'OK') {
          batchMap[batchId].passed++;
        } else {
          batchMap[batchId].failed++;
        }
      });
      
      console.log('Batch Map:', batchMap);
      console.log('Total inspections:', inspections.length);
      
      batches = Object.entries(batchMap)
        .map(([id, stats]) => ({
          id,
          ...stats,
          passRate: stats.total > 0 ? ((stats.passed / stats.total) * 100).toFixed(1) : 0,
          verified: stats.total > 0,
        }))
        .sort((a, b) => b.id.localeCompare(a.id)); // Sort by batch ID descending (newest first)
      
      console.log('Batches:', batches);
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchTraceability();
  });
</script>

<svelte:head><title>{$t('auditor.traceability')} — EPSON QC</title></svelte:head>

<div class="page animate-fade-in">
  <h1 class="page-title">{$t('auditor.traceability')}</h1>
  <p class="subtitle">
    Pelacakan produk berdasarkan batch produksi. 
    <span class="info-badge">ℹ️ Batch dengan prefix "AUTO-" di-generate otomatis dari tanggal inspeksi</span>
  </p>

  {#if error}
    <div class="error-banner">{error}</div>
  {/if}

  {#if loading}
    <div class="loading-state">{$t('common.loading')}</div>
  {:else}
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>{$t('auditor.batch_id')}</th>
          <th>Total Parts</th>
          <th>Passed</th>
          <th>Failed</th>
          <th>Pass Rate</th>
          <th>{$t('auditor.verified')}</th>
        </tr>
      </thead>
      <tbody>
        {#each batches as batch}
          <tr>
            <td>
              <code class:auto-batch={batch.isAutoGenerated}>{batch.id}</code>
            </td>
            <td>{batch.total}</td>
            <td class="ok-text">{batch.passed}</td>
            <td class="ng-text">{batch.failed}</td>
            <td>
              <span class="pass-rate" class:high={batch.passRate >= 95} class:medium={batch.passRate >= 80 && batch.passRate < 95} class:low={batch.passRate < 80}>
                {batch.passRate}%
              </span>
            </td>
            <td>
              <span class="badge" class:badge-ok={batch.verified}>
                {batch.verified ? '✓ ' + $t('auditor.verified') : '✗ Unverified'}
              </span>
            </td>
          </tr>
        {/each}
        {#if batches.length === 0}
          <tr><td colspan="6" class="no-data">{$t('common.no_data')}</td></tr>
        {/if}
      </tbody>
    </table>
  </div>
  {/if}
</div>

<style>
  .page-title { font-size: var(--fs-xl); font-weight: var(--fw-semibold); margin-bottom: var(--sp-2); }
  .subtitle { color: var(--clr-text-dim); font-size: var(--fs-sm); margin-bottom: var(--sp-5); }
  .info-badge { 
    display: inline-block;
    background: var(--clr-surface-2); 
    padding: 2px 8px; 
    border-radius: var(--radius-sm); 
    font-size: var(--fs-xs);
    margin-left: var(--sp-2);
  }
  .error-banner { padding: var(--sp-3); background: var(--clr-ng-bg); color: var(--clr-ng); border-radius: var(--radius-md); font-size: var(--fs-sm); margin-bottom: var(--sp-4); border: 1px solid rgba(239,68,68,0.2); }
  .loading-state { padding: var(--sp-8); text-align: center; color: var(--clr-text-muted); }
  .no-data { text-align: center; color: var(--clr-text-dim); padding: var(--sp-8) !important; }
  code { background: var(--clr-surface-2); padding: 1px 6px; border-radius: 4px; font-size: var(--fs-xs); }
  code.auto-batch { background: rgba(59, 130, 246, 0.1); color: var(--clr-accent); }
  .ok-text { color: var(--clr-ok); font-weight: var(--fw-medium); }
  .ng-text { color: var(--clr-ng); font-weight: var(--fw-medium); }
  .pass-rate { font-weight: var(--fw-semibold); padding: 2px 8px; border-radius: var(--radius-sm); }
  .pass-rate.high { color: var(--clr-ok); background: var(--clr-ok-bg); }
  .pass-rate.medium { color: var(--clr-warning); background: rgba(251, 191, 36, 0.1); }
  .pass-rate.low { color: var(--clr-ng); background: var(--clr-ng-bg); }
</style>
